name: deploy-to-github-pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '18'
      
      # package.jsonの内容でパッケージインストール
      - name: setup app env
        run: |
          rm -rf package-lock.json node_modules
          npm i
      
      # ビルド実行、静的リソースを作る
      - name: build static resources
        run: npm run build
          
      # GitHub Pagesにデプロイする
      - name: deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          token: ${{ secrets.GITHUB_TOKEN }}
          # アプリ直下のbuildディレクトリに生成されるため、指定